print("Hola Mundo!")
print(100*2)
print("Hola Mundo!"+"Como te va?")
print("100+55")
print(100+55)
print("Me llamo \"Guido\"")
print("Esta es una linea\nY esta es otra linea")
print("\tEsta es otra linea")
print("This isn\'t a number")
print("Este signo \\ es una barra invertida")
input('Introduce tu nombre: ')
input('Introduce tu apellido: ')
print('Tu edad es ' + (input('Escribe tu edad: ')) + '?')

